### ISSUE TITLE
Support for no_std environments

### ISSUE THREAD

**Issue by KodrAus** [dtolnay/erased-serde#15]
Hi! I've been using `erased-serde` as the basis for some experiments for [structured logging in `log`](https://github.com/rust-lang-nursery/log/issues/149). It would be great if we could support object-safe `serde` in some `no_std` environments.

I hacked up a [quick proof-of-concept](https://github.com/dtolnay/erased-serde/compare/master...KodrAus:feat/no-std) that relies on at least `alloc` first, just to see what it might look like.

I also came across the [intermediary trait solution](https://github.com/serde-rs/serde/pull/602) which offered support with no extra assumptions. I haven't given it a lot of thought yet, but I guess the ship has sailed on that exact proposal now that we have a stable release of `serde`?

Would you be interested in supporting an `alloc` feature in `erased-serde` like `serde` does? Or would you perhaps rather punt the issue and let the portability lint + unified `std` deal with portability?

**Comment by dtolnay** [comment]
I will read through your proof-of-concept later but yes! I would be interested in no_std support that builds on `alloc`. Thanks so much for pursuing this.

**Comment by attente** [comment]
Hi! Is this something you would consider taking another look at? I ran into this problem while trying to compile a crate depending on both erased-serde and serde_cbor under no-std. I also tried the proof-of-concept branch, but it's a bit out of date :)

I pushed a small example repo to reproduce the problem here: https://github.com/attente/erased-serde-cbor
